const createdAt = '2026-06-01T12:00:00.000Z'

export const demoTables = {
  request_statuses: [
    { id: 'status-solicitado', name: 'Solicitado', sort_order: 1 },
    { id: 'status-cotizando', name: 'Cotizando', sort_order: 2 },
    { id: 'status-en-proceso', name: 'En proceso', sort_order: 3 },
    { id: 'status-entregado', name: 'Entregado', sort_order: 4 },
    { id: 'status-cancelado', name: 'Cancelado', sort_order: 5 },
  ],
  categories: [
    { id: 'cat-bombas', name: 'Bombas y fluidos', created_at: createdAt, updated_at: createdAt },
    { id: 'cat-transmision', name: 'Transmision mecanica', created_at: createdAt, updated_at: createdAt },
    { id: 'cat-control', name: 'Control electrico', created_at: createdAt, updated_at: createdAt },
    { id: 'cat-neumatica', name: 'Neumatica', created_at: createdAt, updated_at: createdAt },
    { id: 'cat-mantenimiento', name: 'Mantenimiento industrial', created_at: createdAt, updated_at: createdAt },
  ],
  subcategories: [
    { id: 'sub-bombas-agua', category_id: 'cat-bombas', name: 'Bombas de agua', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-valvulas', category_id: 'cat-bombas', name: 'Valvulas', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-rodamientos', category_id: 'cat-transmision', name: 'Rodamientos', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-correas', category_id: 'cat-transmision', name: 'Correas', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-sensores', category_id: 'cat-control', name: 'Sensores', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-contactores', category_id: 'cat-control', name: 'Contactores', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-cilindros', category_id: 'cat-neumatica', name: 'Cilindros', created_at: createdAt, updated_at: createdAt },
    { id: 'sub-filtros', category_id: 'cat-mantenimiento', name: 'Filtros', created_at: createdAt, updated_at: createdAt },
  ],
  clients: [
    {
      id: 'client-metalnorte',
      company_name: 'Metalnorte Fabricacion SRL',
      contact_name: 'Laura Medina',
      phone: '809-555-0142',
      email: 'compras@metalnorte.demo',
      address: 'Av. Industrial 24',
      city: 'Santiago',
      country: 'Republica Dominicana',
      notes: 'Cliente demo para pruebas de solicitudes recurrentes.',
      created_at: '2026-05-20T09:15:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'client-caribe-pack',
      company_name: 'Caribe Pack & Procesos',
      contact_name: 'Rafael Ortiz',
      phone: '809-555-0188',
      email: 'mantenimiento@caribepack.demo',
      address: 'Zona Franca Manzana B',
      city: 'Santo Domingo',
      country: 'Republica Dominicana',
      notes: 'Interesado en repuestos para linea de empaque.',
      created_at: '2026-05-18T11:20:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'client-cafe-molino',
      company_name: 'Cafe Molino del Este',
      contact_name: 'Marta Rojas',
      phone: '849-555-0117',
      email: 'operaciones@cafemolino.demo',
      address: 'Parque Industrial Este',
      city: 'La Romana',
      country: 'Republica Dominicana',
      notes: 'Solicita piezas para equipos de proceso y bombeo.',
      created_at: '2026-05-16T15:30:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'client-frio-total',
      company_name: 'Frio Total Industrial',
      contact_name: 'Andres Castillo',
      phone: '829-555-0194',
      email: 'servicio@friototal.demo',
      address: 'Calle Energia 12',
      city: 'Moca',
      country: 'Republica Dominicana',
      notes: 'Cuenta demo con solicitudes urgentes y entregadas.',
      created_at: '2026-05-14T08:45:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'client-agrolinea',
      company_name: 'Agrolinea Norte',
      contact_name: 'Patricia Gomez',
      phone: '809-555-0175',
      email: 'repuestos@agrolinea.demo',
      address: 'Carretera Duarte Km 38',
      city: 'La Vega',
      country: 'Republica Dominicana',
      notes: 'Usado para probar filtros por ciudad y reportes.',
      created_at: '2026-05-10T10:10:00.000Z',
      updated_at: createdAt,
    },
  ],
  products: [
    {
      id: 'product-bomba-centrifuga',
      name: 'Bomba centrifuga 1.5 HP',
      internal_code: 'REP-BC-150',
      manufacturer_code: 'BC150-INOX',
      category_id: 'cat-bombas',
      subcategory_id: 'sub-bombas-agua',
      brand: 'Hidronix',
      description: 'Bomba demo para circulacion de agua en procesos industriales.',
      observations: 'Imagen y datos generados para demo.',
      main_image_url: '/demo-products/bomba-centrifuga.png',
      created_at: '2026-05-25T09:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-rodamiento',
      name: 'Rodamiento sellado 6205-2RS',
      internal_code: 'REP-ROD-6205',
      manufacturer_code: '6205-2RS',
      category_id: 'cat-transmision',
      subcategory_id: 'sub-rodamientos',
      brand: 'AxisPro',
      description: 'Rodamiento radial sellado para motores y transportadores.',
      observations: 'Stock demo para pruebas de solicitudes.',
      main_image_url: '/demo-products/rodamiento-6205.png',
      created_at: '2026-05-24T10:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-correa-v',
      name: 'Correa industrial tipo V A42',
      internal_code: 'REP-COR-A42',
      manufacturer_code: 'A42',
      category_id: 'cat-transmision',
      subcategory_id: 'sub-correas',
      brand: 'BeltMaster',
      description: 'Correa trapezoidal para transmision mecanica ligera.',
      observations: 'Producto de ejemplo para reportes por marca.',
      main_image_url: '/demo-products/correa-a42.png',
      created_at: '2026-05-23T10:30:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-sensor-inductivo',
      name: 'Sensor inductivo M18 PNP',
      internal_code: 'REP-SEN-M18',
      manufacturer_code: 'M18-PNP-NO',
      category_id: 'cat-control',
      subcategory_id: 'sub-sensores',
      brand: 'Voltix',
      description: 'Sensor inductivo demo para deteccion de piezas metalicas.',
      observations: 'Incluye imagen local para prueba de catalogo.',
      main_image_url: '/demo-products/sensor-m18.png',
      created_at: '2026-05-22T12:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-valvula-bola',
      name: 'Valvula de bola inox 1 pulgada',
      internal_code: 'REP-VAL-100',
      manufacturer_code: 'VB-INOX-1',
      category_id: 'cat-bombas',
      subcategory_id: 'sub-valvulas',
      brand: 'FlowTech',
      description: 'Valvula de cierre para lineas de agua y fluidos compatibles.',
      observations: 'Datos inventados para demo publica.',
      main_image_url: '/demo-products/valvula-bola.png',
      created_at: '2026-05-21T14:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-contactor',
      name: 'Contactor tripolar 32A',
      internal_code: 'REP-CON-32A',
      manufacturer_code: 'CT32-220V',
      category_id: 'cat-control',
      subcategory_id: 'sub-contactores',
      brand: 'Electra',
      description: 'Contactor para tableros de control y motores pequenos.',
      observations: 'Puede usarse en importaciones demo.',
      main_image_url: '/demo-products/contactor-32a.png',
      created_at: '2026-05-20T16:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-cilindro-neumatico',
      name: 'Cilindro neumatico 50x100',
      internal_code: 'REP-CIL-50100',
      manufacturer_code: 'CN50-100',
      category_id: 'cat-neumatica',
      subcategory_id: 'sub-cilindros',
      brand: 'PneumaLine',
      description: 'Cilindro demo de doble efecto para automatizacion.',
      observations: 'Imagen local generada.',
      main_image_url: '/demo-products/cilindro-neumatico.png',
      created_at: '2026-05-19T09:00:00.000Z',
      updated_at: createdAt,
    },
    {
      id: 'product-filtro-cartucho',
      name: 'Filtro cartucho 10 micras',
      internal_code: 'REP-FIL-10M',
      manufacturer_code: 'FC10-PP',
      category_id: 'cat-mantenimiento',
      subcategory_id: 'sub-filtros',
      brand: 'Purex',
      description: 'Filtro de cartucho para mantenimiento preventivo.',
      observations: 'Producto demo para exportacion y PDF.',
      main_image_url: '/demo-products/filtro-cartucho.png',
      created_at: '2026-05-18T11:00:00.000Z',
      updated_at: createdAt,
    },
  ],
  requests: [
    {
      id: 'request-001',
      client_id: 'client-metalnorte',
      product_id: 'product-rodamiento',
      quantity: 12,
      request_date: '2026-06-03',
      status_id: 'status-cotizando',
      comments: 'Revisar disponibilidad para mantenimiento semanal.',
      created_at: '2026-06-03T09:20:00.000Z',
      updated_at: '2026-06-03T09:20:00.000Z',
    },
    {
      id: 'request-002',
      client_id: 'client-caribe-pack',
      product_id: 'product-correa-v',
      quantity: 6,
      request_date: '2026-06-04',
      status_id: 'status-en-proceso',
      comments: 'Cliente requiere entrega parcial si hay stock.',
      created_at: '2026-06-04T10:10:00.000Z',
      updated_at: '2026-06-04T10:10:00.000Z',
    },
    {
      id: 'request-003',
      client_id: 'client-cafe-molino',
      product_id: 'product-bomba-centrifuga',
      quantity: 2,
      request_date: '2026-06-05',
      status_id: 'status-solicitado',
      comments: 'Validar conexion electrica antes de cotizar.',
      created_at: '2026-06-05T08:40:00.000Z',
      updated_at: '2026-06-05T08:40:00.000Z',
    },
    {
      id: 'request-004',
      client_id: 'client-frio-total',
      product_id: 'product-sensor-inductivo',
      quantity: 4,
      request_date: '2026-06-05',
      status_id: 'status-entregado',
      comments: 'Entregado para tablero de control demo.',
      created_at: '2026-06-05T13:15:00.000Z',
      updated_at: '2026-06-06T11:00:00.000Z',
    },
    {
      id: 'request-005',
      client_id: 'client-agrolinea',
      product_id: 'product-valvula-bola',
      quantity: 8,
      request_date: '2026-06-06',
      status_id: 'status-cotizando',
      comments: 'Comparar precio por lote de 8 y 12 unidades.',
      created_at: '2026-06-06T15:00:00.000Z',
      updated_at: '2026-06-06T15:00:00.000Z',
    },
    {
      id: 'request-006',
      client_id: 'client-caribe-pack',
      product_id: 'product-contactor',
      quantity: 3,
      request_date: '2026-06-07',
      status_id: 'status-solicitado',
      comments: 'Repuesto para tablero secundario.',
      created_at: '2026-06-07T09:30:00.000Z',
      updated_at: '2026-06-07T09:30:00.000Z',
    },
    {
      id: 'request-007',
      client_id: 'client-metalnorte',
      product_id: 'product-cilindro-neumatico',
      quantity: 5,
      request_date: '2026-06-08',
      status_id: 'status-en-proceso',
      comments: 'Confirmar carrera del cilindro antes de despacho.',
      created_at: '2026-06-08T10:25:00.000Z',
      updated_at: '2026-06-08T10:25:00.000Z',
    },
    {
      id: 'request-008',
      client_id: 'client-cafe-molino',
      product_id: 'product-filtro-cartucho',
      quantity: 20,
      request_date: '2026-06-08',
      status_id: 'status-solicitado',
      comments: 'Pedido demo para reporte de consumo mensual.',
      created_at: '2026-06-08T16:10:00.000Z',
      updated_at: '2026-06-08T16:10:00.000Z',
    },
  ],
  request_status_history: [
    {
      id: 'history-001',
      request_id: 'request-001',
      old_status_id: null,
      new_status_id: 'status-cotizando',
      comment: 'Solicitud demo creada',
      created_at: '2026-06-03T09:20:00.000Z',
    },
    {
      id: 'history-002',
      request_id: 'request-004',
      old_status_id: 'status-en-proceso',
      new_status_id: 'status-entregado',
      comment: 'Solicitud demo entregada',
      created_at: '2026-06-06T11:00:00.000Z',
    },
  ],
}
